PHP 8.4.0 support
pmmp/pthreads pull request #142
Opened 2024-11-17 13:38 UTC by AkmalFairuz

2024-11-17 13:42 UTC, dktapps requested changes

2024-11-17 13:42 UTC, dktapps commented on src/handlers.c
> +#if PHP_MAJOR_VERSION == 8 && PHP_MINOR_VERSION >= 4
```suggestion
#if PHP_VERSION_ID >= 80400
```

2024-11-17 13:42 UTC, dktapps commented on src/prepare.c
> +#if PHP_MAJOR_VERSION == 8 && PHP_MINOR_VERSION < 4
```suggestion
#if PHP_VERSION_ID < 80400
```

2024-11-17 13:42 UTC, dktapps commented on src/store.c
> +#if PHP_MAJOR_VERSION == 8 && PHP_MINOR_VERSION >= 4
```suggestion
#if PHP_VERSION_ID >= 80400
```

2024-11-17 13:42 UTC, dktapps commented
Please provide sources of information for your changes.

2024-11-17 18:18 UTC, dktapps requested changes

2024-11-17 18:18 UTC, dktapps commented on src/prepare.c
> +#endif
This is not removed, it's moved to a different place in the struct to allow internal classes to use it.

2024-11-17 19:15 UTC, dktapps commented
Please add 8.4 here https://github.com/pmmp/ext-pmmpthread/blob/a6f7d2283ee1a5d501760a5ab25a93699ef4c781/.github/workflows/main.yml#L14
and here
https://github.com/pmmp/ext-pmmpthread/blob/a6f7d2283ee1a5d501760a5ab25a93699ef4c781/appveyor.yml#L8

2024-11-17 19:28 UTC, AkmalFairuz commented on appveyor.yml
> +    phpsdk_deps -u -t %VC_VER% -b %PHP_VER% -s %PHP_STABILITY% -a %ARCH% -f -d C:\projects\php-src\deps
PHP 8.4 stable is still not released at https://windows.php.net/downloads/php-sdk/deps/series/ , so I added -s PHP_STABILITY.

2024-11-18 01:49 UTC, dktapps commented
Main branch now supports Windows CI via GitHub Actions (which also has much more comprehensive testing). I'd like to see it run this PR before merging. Please merge the branches and add 8.4 to the Windows CI as well.

2024-11-18 01:54 UTC, dktapps commented
Looks like https://github.com/php/php-src/releases/tag/php-8.4.0RC4 would be better suited for testing

2024-11-18 09:12 UTC, dktapps commented on .github/workflows/main.yml
> +            vs-crt: vs16
This should be vs17, 8.4 uses Visual Studio 2022

2024-11-18 09:13 UTC, dktapps commented on .github/workflows/main.yml
> +            build-type: stable
You don't need to add `stable` for this, it's set by default

2024-11-18 09:14 UTC, dktapps commented on .github/workflows/main.yml
> +            build-type: stable
Never mind, I see the problem

2024-11-18 09:16 UTC, dktapps commented
https://github.com/pmmp/ext-pmmpthread/blob/ed6b7eeda8e6eab54f95c61bd94de69a15d339f6/.github/workflows/main-php-matrix-windows.yml#L24 need to bump this to 2.3.0

2024-11-18 09:37 UTC, AkmalFairuz commented on .github/workflows/main.yml
> +            vs-crt: vs16
Isn't vs17 missing?

https://windows.php.net/downloads/php-sdk/deps/

2024-11-18 20:08 UTC, dktapps commented on .github/workflows/main.yml
> +            vs-crt: vs16
Yeah, you're right. Better use vs16 for now then.

2024-11-18 20:53 UTC, dktapps commented
I've fixed the 8.4 Windows build.

Some of the tests need adapting to PHP 8.4. None of them look to be problematic, but the outputs from 8.4 are different. Closures var_dump() more info, some error messages are different, and some object IDs in outputs changed.

2024-11-26 11:59 UTC, dktapps commented
Do you plan on finishing this PR?

2025-01-10 15:25 UTC, dktapps commented
@AkmalFairuz bump

2025-01-10 15:28 UTC, AkmalFairuz commented
Unfortunately, I don’t plan to finish this PR as I’ve lost interest in projects related to PHP.

2025-01-10 16:08 UTC, dktapps commented
Alright. Thanks for the update.

2025-01-12 17:40 UTC, closed without merging